language: node_js
node_js: '8'
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_03ae3847df38_key -iv $encrypted_03ae3847df38_iv
  -in travis_deploy.enc -out travis_deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 ./travis_deploy
- ssh-add ./travis_deploy
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
- git submodule update --init --recursive
script: yarn deploy:update
